# Build customization
builds:
  - binary: goyoda
    goos:
      - windows
      # - darwin
      - linux
    goarch:
      - amd64
    hooks:
      pre: packr -z
      post: packr clean
sign:
   artifacts: checksum
changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo